### ISSUE TITLE
希望国际化（多语言）支持

### ISSUE THREAD

**Issue by GettionHub** [chengzhongxue/halo-theme-hao#331]
### 你当前使用的版本

v2.7.0

### 描述一下此特性

 主题特别好看，希望增加繁体和英语切换

**Comment by Pollen-Z** [comment]
**顶！**

**Comment by Akuns** [comment]
顶

**Comment by chengzhongxue** [comment]
繁体切换添加了，英语暂时不会添加
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/750caa82-1a9d-454d-ba6f-0816661616f0)

**Comment by kobi1108** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/140871439/2c4ac461-7e77-4ec0-bf03-975c914d9324)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/140871439/c794b8e8-2007-47e7-8020-4c1c9ebde1dd)
切換到繁體中文好像依舊是簡體

**Comment by chengzhongxue** [comment]
只能切换，不能默认繁体

**Comment by kobi1108** [comment]
是有切換繁體中文的按鈕..嗎

**Comment by carolcoral** [comment]
> 是有切換繁體中文的按鈕..嗎

在主题中开启右键菜单即可使用

<img width="1665" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/de18045a-4e82-41fa-b605-452615bb9122">
<img width="974" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/16101bdc-d35a-4712-8903-ad91480aefca">

**Comment by kobi1108** [comment]
已看到 感謝
希望能加在右上功能列

**Comment by chengzhongxue** [comment]
上面按钮太多了

**Comment by kobi1108** [comment]
如果設置功能開關，然後右上最多4/5個自定義按鈕🧐
