### ISSUE TITLE
【顶部控制】热门文章根据文章浏览量主动收集

### ISSUE THREAD

**Issue by carolcoral** [chengzhongxue/halo-theme-hao#345]
### 你当前使用的版本

1.2.0

### 描述一下此特性

1. 在主题控制的“顶部”中的“必看精选”、“热门文章”、“实用教程”能否支持根据文章的访问量、热度等方式主动进行收集，同时能支持手动设置文章和分类
2. 能否支持手动设置这3个类别的重命名需求

### 附加信息

<img width="597" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/35d31dc9-f127-462c-8b4b-e7a81968889f">

**Comment by lanbinshijie** [comment]
重命名和图标修改现已支持

**Comment by carolcoral** [comment]
热门文章实现相关API：https://docs.halo.run/developer-guide/theme/finder-apis/post#listedpostvo

**Comment by carolcoral** [comment]
需要官方支持：https://github.com/halo-dev/halo/issues/3358

**Comment by carolcoral** [comment]
wait
