### ISSUE TITLE
使用Artalk评论，评论中带有图片，右下角弹出的评论显示不友好。

### ISSUE THREAD

**Issue by UPToZ-Core** [chengzhongxue/halo-theme-hao#632]
### 是什么版本出现了此问题？

1.4.7-beta3

### 在线站点地址

https://blog.uptoz.cn/archives/XJMb0qRe

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/73866989/53a2d154-b2e2-47cc-b1b8-e45de18773d5)
应该将图片链接显示成[图片]而不是输出图片链接。

**Comment by carolcoral** [comment]
暂无计划

**Comment by UPToZ-Core** [comment]
大哥，你没计划就没计划啊？为毛直接关闭我的isuss 我鱼佬有计划啊
