### ISSUE TITLE
原生评论框样式有 bug

### ISSUE THREAD

**Issue by king-zhangbn** [chengzhongxue/halo-theme-hao#648]
### 是什么版本出现了此问题？

1.4.7

### 发生了什么？

<img width="309" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/60092461/de24f119-51c8-4c82-8bc5-f9e974837cb2">
<img width="261" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/60092461/1a8caa33-c35a-4c8a-8fb1-8cce0f3e8eb9">

**Comment by king-zhangbn** [comment]
<img width="1557" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/60092461/5cafbb61-2b63-4c32-8ec7-7c71880fdb86">
深色模式下还是白色的，没有覆盖黑色

**Comment by carolcoral** [comment]
深色模式下如果评论框里面还是黑色背景的话整个评论框就看不到了，不建议去处理
