### ISSUE TITLE
很多页面都 404

### ISSUE THREAD

**Issue by vmpykeix3790** [chengzhongxue/halo-theme-hao#656]
### 是什么版本出现了此问题？

1.4.7

### 在线站点地址

https://blog.acecandy.cn:880/

### 发生了什么？

当前很多页面都会报 404，比如/fcircle、/music、/equipments、/todolist等等，从配置页面上也没有找到操作的地方，是版本不对还是我配置错误呢。另外还有就是比如刷新首页之后往下滑动就可能会出现卡顿，然后滑就没有反应，隔一会儿才会恢复。

**Comment by vmpykeix3790** [comment]
<img width="1232" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/136196681/62e8eec3-add4-4d77-be85-8151ce41e272">
fa发现是到这个地方滑不动  是刻意而为的吗

**Comment by carolcoral** [comment]
尝试过重装或重启没呢，我们本地无法复现该情况，在群中群友也未反馈出现该情况。

**Comment by vmpykeix3790** [comment]
重装主题和重启 halo 都试过了   好像还是一样

> 尝试过重装或重启没呢，我们本地无法复现该情况，在群中群友也未反馈出现该情况。

**Comment by carolcoral** [comment]
检查过插件没呢，我看这几个页面都是插件提供的，例如：
`/equipments` 的插件是`我的装备`，检查插件是否是正常安装并启用

**Comment by carolcoral** [comment]
或者卸载对应插件后重装插件试试呢

**Comment by vmpykeix3790** [comment]
> 检查过插件没呢，我看这几个页面都是插件提供的，例如： `/equipments` 的插件是`我的装备`，检查插件是否是正常安装并启用

需要下载哪些插件呢，`我的装备`这个插件我没找到   包括鱼塘这个/fcircle也是  鱼塘后端已经单独安装了  也可以在友链页面展示，但是鱼塘进不去
<img width="1243" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/136196681/0de93182-dcca-41b2-87d6-e57f21fb045d">

**Comment by carolcoral** [comment]
`/equipments` https://github.com/chengzhongxue/plugin-equipments


`/todolist`、`/fcircle`、`/music`不是插件，你需要检查下你的主题配置中是否配置正确
