### ISSUE TITLE
使用自定义cdn地址时无法加载部分css

### ISSUE THREAD

**Issue by Oldming1** [chengzhongxue/halo-theme-hao#663]
### 是什么版本出现了此问题？

1.4.8-beta1

### 发生了什么？

将assets自定义cdn可以访问到该目录，当设置自定义cdn时，所有icon图标无法显示，查看网页加载https://xxx/assets/icon/iconfont.css 直接访问，可以正常读取css文件，但是页面无法加载图标，使用本地设置时，地址为/themes/theme-hao/assets/icon/iconfont.css?v=1.4.8-beta1 可以正常加载图标。
![image](https://github.com/liuzhihang/halo-theme-hao/assets/86954573/05d1a302-f152-4b4d-b9e8-41a0c6f349dc)
是需要cdn地址需要额外配置吗？

**Comment by carolcoral** [comment]
beta版本都没有在线cdn资源，请使用本地资源使用beata版本主题

**Comment by Oldming1** [comment]
> beta版本都没有在线cdn资源，请使用本地资源使用beata版本主题

使用的是beta版本压缩包中的assets文件夹下所有资源放在cdn缓存了。但后台改用自定义的cdn 网站所有的icon图标无法加载。网页前端能查看到：https://cdn.my.site/assets/icon/iconfont.css，确认能访问到css文件，能加载/iconfont.css文件，但图标无法显示。
![image](https://github.com/liuzhihang/halo-theme-hao/assets/86954573/6a592407-5ffe-4ecc-85bf-cfefbc372f86)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/86954573/57da1c7d-4126-4bb1-b431-0a03eea4d7e6)

**Comment by carolcoral** [comment]
资源使用是区分版本号的，所以可能存在问题，具体可以再群里面问下别的群友有没有使用相同场景的

**Comment by Oldming1** [comment]
> 资源使用是区分版本号的，所以可能存在问题，具体可以再群里面问下别的群友有没有使用相同场景的

试了一下。我重新描述一下把。我是想使用自己cdn资源缓存静态文件。我新建了一个静态网站，将github上下载压缩版内的assets文件包含内容放在静态目录了。我的主题设置后台地址为 这个网站/assets 。
所有文件能通过直链访问。我加入主题设置后：出现部分字体图标无法加载
![image](https://github.com/liuzhihang/halo-theme-hao/assets/86954573/ee4e4ecf-c427-45ec-8c18-9d718e2a8022)
具体如图。请问一下需要如何适配自定义的cdn？

**Comment by carolcoral** [comment]
你看看response是什么，请求的状态码是200，请求成功了的

**Comment by Oldming1** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/86954573/ee98abab-aeee-444f-865a-3f5cafa3b49f)
很奇怪。负载加不出来。这个文件是存在的是直接访问链接可以下载。

**Comment by carolcoral** [comment]
可能是请求的ceontent-type的问题，这样，你使用`<script></script>`的方式用全局注入把这些文件注入进去试试呢

**Comment by Oldming1** [comment]
我可能不太会使用script参考gpt
<script>
(function() {
  var css = "@font-face {" +
            "font-family: 'CustomIconFont';" +
            "src: url('https://xxx/hao/templates/assets/icon/iconfont.woff2') format('woff2')," +
            "     url('https://xxx/hao/templates/assets/icon/iconfont.woff') format('woff')," +
            "     url('https://xxx/hao/templates/assets/icon/iconfont.ttf') format('truetype');" +
            "font-weight: normal;" +
            "font-style: normal;" +
            "}";

  var head = document.head || document.getElementsByTagName('head')[0];
  var style = document.createElement('style');

  head.appendChild(style);

  style.type = 'text/css';
  if (style.styleSheet){
    // This is required for IE8 and below.
    style.styleSheet.cssText = css;
  } else {
    style.appendChild(document.createTextNode(css));
  }
})();
</script>
还是存在这个问题。
cdn访问文件会直接下载。不知道和cdn配置有木有关系
