### ISSUE TITLE
顶部首页打字机文字支持自定义URL

### ISSUE THREAD

**Issue by bearslyricattack** [chengzhongxue/halo-theme-hao#665]
### 你当前使用的版本

1.4.7

### 描述一下此特性

当前版本下 首页主题的第一屏展示文字只能自己一个一个在后台定义 或者是用随机文字 无法使用自定义的url展示文字
这对不会前端的博客使用者不太友好 建议增加可以使用自定义url展示文字的功能，并定义接口的返回格式。

**Comment by bearslyricattack** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/108731841/70705fa7-e881-43b6-a386-52b3090a5255)

**Comment by carolcoral** [comment]
谁来提供接口，有这种文字api么

**Comment by carolcoral** [comment]
暂时不会考虑实现该功能
