### ISSUE TITLE
bannar 宽度适应问题

### ISSUE THREAD

**Issue by vmpykeix3790** [chengzhongxue/halo-theme-hao#668]
### 是什么版本出现了此问题？

1.4.8

### 在线站点地址

https://blog.acecandy.cn:880/

### 发生了什么？

我用笔记本浏览器调整顶部banner发现一直无法生效，以为是废弃配置，但是无意间把我的 edge 的垂直标签页关了发现出现了真实应该出现的界面

打开垂直标签页
<img width="1231" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/136196681/106081e9-014b-41ef-9a48-87ad9be026f1">

关闭垂直标签页
<img width="1391" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/136196681/a9b1328b-e420-4fde-85c3-d76109c59ed6">

应该是触发了宽度自适应的 style，直接调整浏览器窗口大小也会发现问题

**Comment by carolcoral** [comment]
抱歉，这块确实没考虑垂直菜单的情况，目前也不太好修复

**Comment by carolcoral** [comment]
这个需要官方提供finder方法用来判断菜单是垂直菜单还是水平菜单，然后才能进一步控制显示的banner个数，垂直菜单显示2个就合适了

**Comment by carolcoral** [comment]
该样式在新版本中已经被删除了——1.4.9
