### ISSUE TITLE
侧边栏最新文章显示与置顶文章冲突

### ISSUE THREAD

**Issue by 666ghj** [chengzhongxue/halo-theme-hao#671]
### 是什么版本出现了此问题？

hao版本：1.4.8
halo版本：2.12.4

### 在线站点地址

http://lovexl.top

### 发生了什么？

如在线站点地址中展示的，给部分文章添加置顶显示后，侧边栏的最新文章也会被置顶文章占用，从而导致无法显示真正的最新发布的文章

**Comment by carolcoral** [comment]
侧边栏中“最新文章”使用的是获取文章列表第一页的方式进行展示的，目前无法有效的获取到“最新文章”，需要官方提供相应Finder才行。建议找halo官方提issues。
<img width="1121" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/4646ff89-0b4e-4f4f-8d4f-546a39423644">

**Comment by 666ghj** [comment]
有啦，halo的14版本提供了该类api了终于😍

**Comment by carolcoral** [comment]
> 有啦，halo的14版本提供了该类api了终于😍

回头看看，上次2.14版本会议说的是2.15才出

**Comment by carolcoral** [comment]
@666ghj 看过了，2.14的文档里面没有相关api，你发来看看：https://docs.halo.run/developer-guide/theme/finder-apis/post

**Comment by carolcoral** [comment]
本来说2.15有api的，结果还是没有

**Comment by 666ghj** [comment]
> 本来说2.15有api的，结果还是没有

🥹

**Comment by alwayszhangyu** [comment]
我看了halo官方的api，我认为可以使用archives(page,size)或archives(page,size,year)来代替现在主题使用的list(page,size)。



 list(page,size)的描述是：根据分页参数获取文章列表。

 list，这里我理解为首页的文章列表，这里面的排列方式虽然也按时间顺序进行排列，但添加了一个额外的条件，置顶。



archives(page,size)的描述是：根据分页参数获取文章归档列表。

archives(page,size,year)的描述是：根据年份和分页参数获取文章归档列表。

archives，这里我理解为归档的文章列表，这里面的排列方式只按时间进行排序，是不管是否置顶的。



使最新发布列表与归档列表（/archives）相同就行了，如下图所示。

![image-20240519143342257](https://houxiongxiong-1310114553.cos.ap-chengdu.myqcloud.com/typora/202405191433402.png)

思路仅供参考

**Comment by carolcoral** [comment]
如果置顶文章和最新文章在相同年份呢，这样还是没法获取实际想要的最新文章列表的

**Comment by alwayszhangyu** [comment]
场景：有9篇文章，其中**测试6{置顶}**与**置顶**是已置顶的文章，其余的是正常文章，如下：


![image-20240519230236501](https://houxiongxiong-1310114553.cos.ap-chengdu.myqcloud.com/typora/202405192302575.png)


下面是完全复制**[[archives(page,size)](https://docs.halo.run/developer-guide/theme/finder-apis/post#archivespagesize)](https://docs.halo.run/developer-guide/theme/finder-apis/post#archivespagesize)**官方示例进行的修改


```html
<div class="card-widget card-recent-post" th:with='posts = ${postFinder.archives(1,theme.config.sidebar.recentPost)},
    postRandomImg=${#strings.contains(theme.config.layout.postRandomImg,"?") ? theme.config.layout.postRandomImg+"&" : theme.config.layout.postRandomImg+"?"}'>
    <div class="item-headline"><i class="haofont hao-icon-eicon_map-2-line1"></i><span>最近发布</span></div>
    <div class="aside-list">
         <!-- 修改处分界线 -->
        <th:block th:with="archives = ${postFinder.archives(1,10)}">
            <th:block th:each="archive : ${archives.items}">
                <h1 th:text="${archive.year}"></h1>
                <ul>
                    <th:block th:each="month : ${archive.months}">
                        <li th:each="post : ${month.posts}">
                            <a th:href="@{${post.status.permalink}}" th:text="${post.spec.title}">
                            </a>
                        </li>
                    </th:block>
                </ul>
            </th:block>
        </th:block>
		<!-- 修改处分界线 -->
    </div>
</div>
```


![image-20240519225106774](https://houxiongxiong-1310114553.cos.ap-chengdu.myqcloud.com/typora/202405192251828.png)


结果：


**测试6{置顶}**与**置顶**在文章列表是正常排列的，在最近发布是按时间由近及远排序的，不受**测试6{置顶}**与**置顶**的置顶效果影响。（不会写样式，将就着哈！）


![image-20240519225434374](https://houxiongxiong-1310114553.cos.ap-chengdu.myqcloud.com/typora/202405192254437.png)


![image-20240519232543298](https://houxiongxiong-1310114553.cos.ap-chengdu.myqcloud.com/typora/202405192325552.png)


下面是未修改的最近文章：可以看到置顶的优先级最高


![image-20240519231222391](https://houxiongxiong-1310114553.cos.ap-chengdu.myqcloud.com/typora/202405192312605.png)

**Comment by carolcoral** [comment]
@chengzhongxue 鱼，来活啦

**Comment by chengzhongxue** [comment]
这里是要改成最热门文章，而不是最新文章这样

**Comment by carolcoral** [comment]
> 这里是要改成最热门文章，而不是最新文章这样

侧边栏的“最新文章”

**Comment by chengzhongxue** [comment]
下个版本更新

**Comment by chengzhongxue** [comment]
1.5.3版本修复此问题
