### ISSUE TITLE
手机端无法显示右侧栏

### ISSUE THREAD

**Issue by Newzealcoin** [chengzhongxue/halo-theme-hao#673]
### 是什么版本出现了此问题？

 1.4.8

### 在线站点地址

http://39.106.0.238:8080/

### 发生了什么？

1、手机端在1级界面可以打开右侧的栏，但是在“任何”2级界面都无法打开右侧栏，尝试过重启docker、重新安装主题、卸载所有插件依然无法解决。（通过重新安装docker以及1panel和主题已经得到暂时性的解决）
<img width="309" alt="微信图片_20240229094304" src="https://github.com/liuzhihang/halo-theme-hao/assets/87095959/b69a9c89-23cc-444f-a10d-191fb0eec80a">

2、移动端的右侧栏有BUG，不管菜单栏如何更改顺序，移动端的右侧栏始终无法更改排序。

**Comment by Newzealcoin** [comment]
关于第二个bug的补充
电脑端正常 手机端显示和电脑端不匹配 
按理说我调整《主菜单》顺序，手机端和电脑端的也会跟着调整，实际上并不是，只能随机显示一部分…

再补充一个bug 
手机端登录页面不见了


再再补充一个bug
手机端左上角无法调出 电脑端可以

总结 都是手机惹的货🥹

**Comment by carolcoral** [comment]
1. 移动端右侧菜单需要在主题中配置“左侧菜单”，该菜单对应的是PC端的坐车菜单
2. 移动端没有左侧菜单
3. 移动端右侧菜单的顺序需要调整“左侧菜单”顺序
4. PC端左侧菜单即移动端右侧菜单需要至少配置2级菜单才能生效
