### ISSUE TITLE
亮主题下评论输入框样式问题，强迫症接受不了，希望大佬修复

### ISSUE THREAD

**Issue by lxz946786639** [chengzhongxue/halo-theme-hao#675]
### 是什么版本出现了此问题？

 1.4.8

### 在线站点地址

https://liuzhihang.com/moments

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/40382425/d17f46c3-5034-44bf-8943-312136c7ae52)

**Comment by carolcoral** [comment]
麻烦详细说明下，没看出什么问题呢
