### ISSUE TITLE
侧边栏配置小部件统计问题

### ISSUE THREAD

**Issue by good2luck** [chengzhongxue/halo-theme-hao#693]
### 是什么版本出现了此问题？

1.4.8

### 在线站点地址

https://xudj.top/

### 发生了什么？

侧边栏配置小部件，使用stat、tags-stat，没有按月统计吗？我看演示网站中是有按月统计的信息，这个是啥原因呢？

**Comment by carolcoral** [comment]
目前暂时没有按月统计的
