### ISSUE TITLE
Artalk POST /api/stat出错

### ISSUE THREAD

**Issue by HeLongaa** [chengzhongxue/halo-theme-hao#703]
### 是什么版本出现了此问题？

1.4.8

### 在线站点地址

https://blog.duolaa.asia/

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/71657914/04968bba-d47c-45db-a266-8a7ca26784d3)

POST /api/stat 出错，查看Artalk相关问题：

> v2.8.0 重构了 HTTP API.
> GET /api/conf 修改为 GET /api/v2/conf
> 同样还有常用的 POST /api/stat 修改为 GET /api/v2/stats/{type}
> 我们提供 Swagger.json 和 API 文档供参考：https://artalk.js.org/http-api

希望修复，万分感激！

**Comment by carolcoral** [comment]
好的，收到

**Comment by carolcoral** [comment]
为了兼容历史版本的接口，建议在你本地的artalk服务器上使用代理方式做一次端口转发，主题中暂时不会修改，只需要转发
```nginx
/api/stat -> /api/v2/stats
```

**Comment by carolcoral** [comment]
你先试试这个测试包，我没环境方便测试
[归档.zip](https://github.com/liuzhihang/halo-theme-hao/files/14784406/default.zip)

**Comment by HeLongaa** [comment]
等我回去在开发环境试试看，感谢感谢

**Comment by HeLongaa** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/71657914/131b28a2-2a4f-4d3e-b7de-eb89e7ab41ac)
问题依旧，已安装1.4.9-beta1

**Comment by carolcoral** [comment]
> ![image](https://private-user-images.githubusercontent.com/71657914/317704826-131b28a2-2a4f-4d3e-b7de-eb89e7ab41ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Nzk3MjYsIm5iZiI6MTcxMTY3OTQyNiwicGF0aCI6Ii83MTY1NzkxNC8zMTc3MDQ4MjYtMTMxYjI4YTItMmE0Zi00ZDNlLWI3ZGUtZWI4OWU3YWI0MWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAyMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NTBlODk1YjllMjY0ODViNjBkYjlkNDRjZDIwZTlkZDdiMDg5ZjQyNzFjOGNiMTZiNWYzYTU5MDJiOGQ4Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fHXZSNMwzS0ODo9wQk4m5sh62RGas1Ia2PEL1iXA3hA) 问题依旧，已安装1.4.9-beta1

你安装后需要：
1. 选择本地资源（因为CDN资源未发布）
2. 重启halo容器

**Comment by HeLongaa** [comment]
已解决问题，感谢回复
