### ISSUE TITLE
halo升级 2.14.0 文章侧边栏图片出现问题

### ISSUE THREAD

**Issue by xiaodunxin** [chengzhongxue/halo-theme-hao#707]
### 是什么版本出现了此问题？

1.4.8

### 在线站点地址

https://blog.xiaoxin.space/

### halo 从 2.13.1 升级到 2.14.0 ，侧边栏图片出现问题。
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/58406805/2a60e522-92e2-4c1a-abbe-659c04342956)
### 首页/标签和分类页可正常显示
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/58406805/5cb615f9-8a03-4be0-baf4-1dff568e53e5)
### 文章的图片显示异常
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/58406805/94ece0f0-d96e-453b-9b0b-6fcad84302ae)

**Comment by carolcoral** [comment]
先看缓存

**Comment by xiaodunxin** [comment]
有尝试过使用无痕浏览的模式，问题依然存在

**Comment by xiaodunxin** [comment]
> 先看缓存

有尝试过使用无痕浏览的模式，问题依然存在

**Comment by carolcoral** [comment]
不要用默认的背景地址了，这个地址已经挂了
<img width="880" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/60b2b2a6-8416-4118-ba61-d1f325558bae">

**Comment by carolcoral** [comment]
如果要用这个的话建议在主题设置`其他`里面选择资源为`本地`

**Comment by xiaodunxin** [comment]
> 如果要用这个的话建议在主题设置`其他`里面选择资源为`本地`

资源是选择本地...更新完 1.4.9 ，这个issue所描述的图片问题自动修复了！！！我擦嘞，emo了
