### ISSUE TITLE
随便逛逛新版与旧版的选项

### ISSUE THREAD

**Issue by kxkl2077** [chengzhongxue/halo-theme-hao#711]
### 你当前使用的版本

1.4.9

### 描述一下此特性

![image](https://github.com/chengzhongxue/halo-theme-hao/assets/110510729/61989aee-e1b1-4f59-bcd0-b52dbfd79e22)
这个组件改的感觉不咋好看，能不能出一个选项，一个是1.4.9改的新版，一个是1.4.8之前的旧版
如果这个选项早就有了，那就当我没说（

**Comment by carolcoral** [comment]
1.5.0-beta1 版本左侧banner新增了轮播图样式，老样式以后在看会不会兼容了，可能性比较小

**Comment by carolcoral** [comment]
https://github.com/chengzhongxue/halo-theme-hao/discussions/715

**Comment by BaoChn** [comment]
我调了个样式，你代码注入试试😎
```
@media screen and (min-width: 1200px) {
  .banners-link-btn {
    width: auto;
  }
  .banners-link-title {
    margin-left: 8px;
  }
  .banners-title {
    left: 2rem;
    font-size: 2em;
  }
  .banners-title-small {
    font-size: 18px;
  }
  .tags-group-all {
  transform: rotate(30deg);
  }
  #bannerGroup .tags-group-wrapper {
  width: 560px;
  }
}
```

**Comment by 2019YKL** [comment]
确实感觉改得更丑了，至少左侧两个按钮宽度可以长点，没必要空一大段在那边。
