### ISSUE TITLE
页脚信息会被ADGuard广告插件拦截，不想显示页面，但是得显示ICP备案和公安备案信息

### ISSUE THREAD

**Issue by lcy3189** [chengzhongxue/halo-theme-hao#712]
### 描述一下此特性

![Snipaste_2024-04-10_15-34-00](https://github.com/chengzhongxue/halo-theme-hao/assets/159663900/09dbaccf-2363-46eb-9aca-e2c885eb978a)
广告插件屏蔽页脚后，不会显示ICP和公安备案信息，可以这两个参数不放入页脚吗？

**Comment by lcy3189** [comment]
![Uploading Snipaste_2024-04-10_15-36-52.png…]()

**Comment by lcy3189** [comment]
![Snipaste_2024-04-10_15-36-52](https://github.com/chengzhongxue/halo-theme-hao/assets/159663900/6079da2a-55ad-4762-b980-8a6abec724c3)

**Comment by carolcoral** [comment]
1. 关闭页脚设置
2. 在底部徽标中设置

<img width="1493" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/86936c4f-fd41-416c-b45a-2831cf258656">
<img width="602" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/029fec83-a433-4207-b0f7-33777e2ddc4c">
<img width="571" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/873a9918-2a16-4b43-8ac7-e3a4f8845c67">

**Comment by lcy3189** [comment]
> 1. 关闭页脚设置
> 2. 在底部徽标中设置
> 
> <img alt="image" width="1493" src="https://private-user-images.githubusercontent.com/8952687/321456988-86936c4f-fd41-416c-b45a-2831cf258656.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDAyMzQsIm5iZiI6MTcxMjc5OTkzNCwicGF0aCI6Ii84OTUyNjg3LzMyMTQ1Njk4OC04NjkzNmM0Zi1mZDQxLTQxNmMtYjQ1YS0yODMxY2YyNTg2NTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDE0NTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQyZTk5NTNkM2EzYzhlNTBkOGQ3MzI5NDdkZjgxMDI1NjEzYjQ0ODE1NjliYWRiOTdkYjc4NDFiNDY1N2RlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A_6CAGg1SHdYpYzMtbD6HZK7lAEMq6SrhBxJu4u0P4I"> <img alt="image" width="602" src="https://private-user-images.githubusercontent.com/8952687/321457809-029fec83-a433-4207-b0f7-33777e2ddc4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDAyMzQsIm5iZiI6MTcxMjc5OTkzNCwicGF0aCI6Ii84OTUyNjg3LzMyMTQ1NzgwOS0wMjlmZWM4My1hNDMzLTQyMDctYjBmNy0zMzc3N2UyZGRjNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDE0NTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzZhZjNmZWRlNTNiYTI5Yzg1NmU4OWM4OTU4ZTQ2ZmYyZDFjOGY3ZTY4NDA1MzlkYWYwODU1YzllM2JmOTIxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Xb5yTk_4dal_8pw4wOPjd0geMa4dHHclEe9FMZWhG4"> <img alt="image" width="571" src="https://private-user-images.githubusercontent.com/8952687/321457872-873a9918-2a16-4b43-8ac7-e3a4f8845c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDAyMzQsIm5iZiI6MTcxMjc5OTkzNCwicGF0aCI6Ii84OTUyNjg3LzMyMTQ1Nzg3Mi04NzNhOTkxOC0yYTE2LTRiNDMtOGFjNy1lM2E0Zjg4NDVjNjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDE0NTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY4NTUyOGI2YjM0MDJmOGNkZTc2MzI5M2Y5ZTYzNmM5MTNmNjRhMDZkZTZmOWIyMjQ3ODRmMGJlOWNjZWM4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WZlDLxmiprxRCnWW7dXrfxc19wPu6Iz4Dg8ev9Aq4-o">

已解决，十分感谢！
