### ISSUE TITLE
更新版本后顶部Banner 错位

### ISSUE THREAD

**Issue by xJoyLu** [chengzhongxue/halo-theme-hao#717]
### 是什么版本出现了此问题？

1.5.0 beta1

### 在线站点地址

https://ldd.cc

### 发生了什么？

第一时间更新到 1.5.0 beta1
更新后首页 Banner 处错误
后台对应编辑项不可用，见图
<img width="1598" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/74151622/98de9508-da69-4363-8319-a07f62afb4cf">
<img width="720" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/74151622/ee6a7950-0de3-432a-84bc-991b0432a934">

**Comment by carolcoral** [comment]
嗯，我看下原因，很奇怪，没有动默认样式的代码。。

**Comment by carolcoral** [comment]
calc() 函数问题，马上修复下

**Comment by carolcoral** [comment]
重新下载试试

**Comment by xJoyLu** [comment]
安排

**Comment by xJoyLu** [comment]
重新下载 1.5.0 beta1 版本吗？看到帖子还没有被更新

**Comment by carolcoral** [comment]
> 重新下载 1.5.0 beta1 版本吗？看到帖子还没有被更新

包我更新了，重新下载包就行

**Comment by carolcoral** [comment]
重启下容器试试，另外设置中资源要选择`本地`

**Comment by xJoyLu** [comment]
容器重启了，OpenResty 也进行了重启，重载。
主题设置中的资源没有做修改。

**Comment by carolcoral** [comment]
> 容器重启了，OpenResty 也进行了重启，重载。 主题设置中的资源没有做修改。 halo 也更新至最新的 `2.1.4` 版本

额，最新版本的halo是`2.14.0-rc.3`

**Comment by xJoyLu** [comment]
是的，我打错了
<img width="595" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/74151622/77f7a63e-57b8-4387-b2f2-0be9bd96fb77">
里面的「重建」、「重启」、「同步」都尝试过点击了...

**Comment by xJoyLu** [comment]
问题解决。
<img width="1388" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/74151622/1ac3517c-23e1-4c28-91b8-d245fd2651c1">
cf 做修改需要关缓存，否则会出现奇奇怪怪的问题
