### ISSUE TITLE
这个双语切换能不能从繁体改为英文,本人在国外,很想给朋友同学看

### ISSUE THREAD

**Issue by lucky9peach** [chengzhongxue/halo-theme-hao#721]
### 你当前使用的版本

 1.4.9

### 描述一下此特性

很需要一个英文,如果可以,我可以自己添加,有没有说明文档呀

**Comment by carolcoral** [comment]
暂时还不支持英文

**Comment by carolcoral** [comment]
要halo官方支持才行，不然就需要改每个文件的内容，全部改成英文的

**Comment by carolcoral** [comment]
你也可以尝试自己改改，把项目pull到本地后，修改`～/template/modules` 和 `～/template` 下的所有html文件中所有中文内容改成英文的即可，然后打包上传主题
