### ISSUE TITLE
页脚自定义彩色 icon ，会被自动加黑色底色 ，请移除这特性或者增加配置能选择是否启用这特性

### ISSUE THREAD

**Issue by xiaodunxin** [chengzhongxue/halo-theme-hao#723]
### 你当前使用的版本

1.4.9

### 描述一下此特性

页脚自定义彩色 icon ，会被自动加黑色底色 ，请移除这特性或者增加配置能选择是否启用这特性
现在效果：
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/58406805/9866b30d-7e7d-44a7-b73b-46d16626ffa1)
希望效果：
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/58406805/905932e6-5a7a-4e60-b979-0985e0550d38)

**Comment by carolcoral** [comment]
可以计划
