### ISSUE TITLE
访问量未更新

### ISSUE THREAD

**Issue by lakersWin** [chengzhongxue/halo-theme-hao#726]
### 是什么版本出现了此问题？

1.4.9

### 发生了什么？

1、更换过主题之后，直接点击首页访问某个文章，访问量不会更新
2、从搜索中搜到的文章点击后会更新访问量

对比缺少一个counter的访问
/apis/api.halo.run/v1alpha1/trackers/counter

不知道是不是这个原因。

**Comment by carolcoral** [comment]
@chengzhongxue
