### ISSUE TITLE
可否将底部徽标title显示在徽标右侧

### ISSUE THREAD

**Issue by yulongsa** [chengzhongxue/halo-theme-hao#727]
![S40424-21131967_com.microsoft.emmx.png](https://github.com/chengzhongxue/halo-theme-hao/assets/13462017/d55fa9fb-1f61-400f-ba16-c5767e2fbc30)

徽标titile填写后显示在右侧，不填写仅显示徽标这样挺不错的。

**Comment by carolcoral** [comment]
title只是影响的alt，你在设置底部图标的时候用img就可以啊

**Comment by carolcoral** [comment]
实际展示收到的主要是这个配置的影响
<img width="529" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/55ac1267-2cb2-4903-911e-10b6b849044a">

**Comment by carolcoral** [comment]
<img width="171" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/3c886c64-1b05-4727-bc9a-05959f439f21">

**Comment by yulongsa** [comment]
好的，感谢
