### ISSUE TITLE
第一屏打印机显示的文字底色白条闪烁

### ISSUE THREAD

**Issue by qiao-huan** [chengzhongxue/halo-theme-hao#729]
### 你当前使用的版本

1.4.9

### 描述一下此特性

本主题有一个功能：“顶部——首页第一屏——打字机显示的文字”。

在这里设置好文字后，打开个人博客，会在第一屏显示博客名称和打印机显示的文字。

但是在这个加载的过程中，会有两个白色的条状文字底色被首先加载，然后伴随着文字再加载出来，如附图所示。

这个白色的条带由于一闪而过，比较影响视觉的美观性，而且黑夜打开博客的话闪烁比较晃眼。

希望能在新版本中取消这个白色条带的闪烁效果

![halo_hao_issue1](https://github.com/chengzhongxue/halo-theme-hao/assets/56923532/d96d2151-915f-47a0-a85b-bcdc77c6e1a3)
![halo_hao_issue2](https://github.com/chengzhongxue/halo-theme-hao/assets/56923532/d8877240-349b-4f57-99f0-0e8c7a49d46e)

**Comment by qiao-huan** [comment]
或者可以麻烦作者大人大致说一下，这个可以去源码的那个地方改吗，我可以自己去改一下，谢谢作者大人

**Comment by QingFeng-awa** [comment]
这个白色的不是加载动画么

**Comment by QingFeng-awa** [comment]
而且,这个加载动画直接删掉我个人不赞成,不如允许在设置里开关这个动画。

**Comment by qiao-huan** [comment]
> 这个白色的不是加载动画么

是的，是加载动画

**Comment by qiao-huan** [comment]
> 而且,这个加载动画直接删掉我个人不赞成,不如允许在设置里开关这个动画。

设置开关，我也认为是一个好的方案
