### ISSUE TITLE
用户无法从右上角登入按钮进行退出

### ISSUE THREAD

**Issue by yumuing** [chengzhongxue/halo-theme-hao#730]
### 是什么版本出现了此问题？

halo 2.14版本 hao主题1.49版本 chrome浏览器

### 在线站点地址

本地运行

### 发生了什么？

选择退出登录后，自动返回首页，右上角登入按钮头像正常显示，点击又可进行退出登录，且进入个人中心也无退出，但个人中心处退出按钮可退出。同时，非管理员身份登入选项中不应为控制台，而应为个人中心。

**Comment by carolcoral** [comment]
这个应该找halo官方，主题无法控制登录后台操作的，且目前我们无法本地复现
