### ISSUE TITLE
在线工具无自适应宽度

### ISSUE THREAD

**Issue by yumuing** [chengzhongxue/halo-theme-hao#731]
### 是什么版本出现了此问题？

halo 2.14版本 hao主题1.49版本 chrome浏览器

### 在线站点地址

本地运行

### 发生了什么？

![image](https://github.com/chengzhongxue/halo-theme-hao/assets/77838031/4eeab1e7-7c64-4b62-9341-321cf31f55bc)
文字自动省略，无自适应宽度

**Comment by carolcoral** [comment]
没有复现呢
<img width="1410" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/7f6c7a59-b2a2-4b30-8adb-705bd1d06f3d">
<img width="1386" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/53d26189-00d1-4f22-b7c9-39b394970ac3">
