### ISSUE TITLE
无法更新到主题版本1.5.1 ，提示版本不兼容

### ISSUE THREAD

**Issue by hjdyzy** [chengzhongxue/halo-theme-hao#737]
### 是什么版本出现了此问题？

主题版本1.4.9，halo版本2.14.1

### 发生了什么？

halo专业版 版本2.14.1 在应用市场无法申请主题版本，显示版本不兼容

### 附加信息

![image](https://github.com/chengzhongxue/halo-theme-hao/assets/71299416/c27dedd1-2074-4c66-ac75-556b6f4688b4)
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/71299416/9b947656-7274-4ac5-8a68-558737dd61d5)

**Comment by carolcoral** [comment]
需要halo更新到2.15.0-rc1 及以上版本
