### ISSUE TITLE
侧边栏标题夜间模式适配问题

### ISSUE THREAD

**Issue by SakuraU0** [chengzhongxue/halo-theme-hao#742]
### 是什么版本出现了此问题？

 1.5.1

### 发生了什么？

主页侧边栏在夜间模式时也显示黑色，尝试过完全卸载主题重装也是这样。
看了一下样式，不知道从哪里继承了一个body的样式
![screenshot-20240506-155552](https://github.com/chengzhongxue/halo-theme-hao/assets/44707377/27fe2309-adf0-4fe5-a51b-ab718a4804c6)

**Comment by Japerz12138** [comment]
同问题，版本1.5.1。我这边不只是侧边栏，footer，以及统计信息均在深色模式下为黑色。其他页面显示正常。
![PixPin_2024-05-12_01-22-32](https://github.com/chengzhongxue/halo-theme-hao/assets/30984308/4fd451c9-d3ec-4322-97a8-e407916618c1)
![PixPin_2024-05-12_01-22-22](https://github.com/chengzhongxue/halo-theme-hao/assets/30984308/7c277cda-7ba4-4599-bfc0-9778147ee1db)
![PixPin_2024-05-12_01-24-05](https://github.com/chengzhongxue/halo-theme-hao/assets/30984308/60857f26-ed53-4f0d-840e-9127ad724986)

**Comment by chengzhongxue** [comment]
下个版本修复
