### ISSUE TITLE
当设置了全局透明背景背景图开启夜间模式, 导航栏呈现透明不可见状态, 以及夜间模式下背景图匹配问题

### ISSUE THREAD

**Issue by bit15k** [chengzhongxue/halo-theme-hao#744]
### 是什么版本出现了此问题？

主题版本1.5.1 halo版本2.15.0

### 在线站点地址

[https://bytevoyage.site/](https://bytevoyage.site/)

### 发生了什么？

当设置全局透明背景图, 在夜间模式下滑动到最顶部会出现导航栏透明不可见, 如下框选部分应该显示导航栏但透明
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/29975541/28076184-e15a-4896-9938-1a66c168bf3e)只有上滑在没有到最顶部时才会显示正常
![](https://imgs-jsdelivr.bytevoyage.site/imgs/202405081550358.png)
设置全局透明背景图后, 夜间模式仍然显示透明背景图与夜间模式全黑不协调, 建议增加开启夜间模式下自动关闭全局透明背景图或者增加夜间模式下单独设置一张全局透明背景图

**Comment by carolcoral** [comment]
嗯，因为我一般不用夜间模式，所以没考虑到，后面修复
