### ISSUE TITLE
主页进入到文章详情页，markdown 代码块未加载出来，刷新后重新加载出来

### ISSUE THREAD

**Issue by pugsswangxs** [chengzhongxue/halo-theme-hao#745]
### 是什么版本出现了此问题？

 1.5.2

### 在线站点地址

https://www.testerwangxinsheng.top/

### 发生了什么？

从主页进去到文章详情页后，文章内的部分代码块格式没有加载出来。刷新页面后，代码块加载出来。

### 附加信息

ko控制台报错如下：
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/91642824/33db95eb-774f-4bf4-9d11-0529667f46c0)

复现如下
https://github.com/chengzhongxue/halo-theme-hao/assets/91642824/365b909e-4746-4c8f-8cff-80dc235a22b8

**Comment by chengzhongxue** [comment]
主题带了代码块插件，不需要自己去使用代码块插件，你这是冲突了
