### ISSUE TITLE
修改头像的时候出现在裁剪页面出现问题

### ISSUE THREAD

**Issue by zuoan77** [chengzhongxue/halo-theme-hao#747]
### 是什么版本出现了此问题？

2.15.2

### 发生了什么？

<img width="1239" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/133548090/ed340bae-6402-4f8e-932c-e574555257e7">

**Comment by XiaoWoUi** [comment]
这是 Halo 方面的问题，移步到 Halo 问吧
