### ISSUE TITLE
不支持 Halo 原生的插件化评论

### ISSUE THREAD

**Issue by ichenhe** [chengzhongxue/halo-theme-hao#751]
### 是什么版本出现了此问题？

1.5.2

### 发生了什么？

安装第三方评论插件后，Hao 评论设置为「默认」，无法显示评论组件。
关联 Issue: https://github.com/ichenhe/halo-twikoo/issues/2

> 知道 Hao 内置了部分第三方评论系统的支持，是否因此破坏了对原生评论的兼容性？

**Comment by carolcoral** [comment]
并没有，我们使用都是正常的，应该是你哪儿没配置对

**Comment by chengzhongxue** [comment]
建议用主题只带的，没必要用插件
