### ISSUE TITLE
又拍云联盟跳转地址更改及Meting引用

### ISSUE THREAD

**Issue by Xiaotingwen** [chengzhongxue/halo-theme-hao#754]
### 你当前使用的版本

1.5.2

### 描述一下此特性

鱼老板好~近期发现了下面两个问题，老板能更新一下吗，哈哈哈哈哈哈~
1.又拍云联盟底部的链接
这两天申请又拍云的时候链接无法通过审核，需要更改为https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral

2.音乐部件引用，看了一下Meting的官方文档，如果是国外服务器部署的api需要更改前端JS引用才能使用QQ音乐的源，测试了一下，目前咱们主题的JS无法播放，把官方给的JS注入全局是可以正常播放QQ音乐的。能播放是注入了以下两个JS
<script src="https://unpkg.com/aplayer/dist/APlayer.min.js"></script>
<script src="https://unpkg.com/@xizeyoupan/meting@latest/dist/Meting.min.js"></script>

坐等鱼佬更新~~~

**Comment by carolcoral** [comment]
@xindi520 第一个问题你可以在`页脚` - `云服务商`里面选择自定义地址填写，第一个填写图片地址，第二个填写跳转地址
