### ISSUE TITLE
halo 2.16.4 这个版本, hao 主题某些功能失效

### ISSUE THREAD

**Issue by zscmmm** [chengzhongxue/halo-theme-hao#755]
### 是什么版本出现了此问题？

halo 2.16.4 

### 发生了什么？

设置主题的时候某些功能失效

### 附加信息

1. 给侧边栏内容添加`文章标签`, 在文章出不显示
<img width="500" alt="图片" src="https://github.com/chengzhongxue/halo-theme-hao/assets/111739721/3bfd3f7a-fe08-42f1-9499-591cb604e944">

显示如下空白

<img width="321" alt="图片" src="https://github.com/chengzhongxue/halo-theme-hao/assets/111739721/9335796b-85b7-407a-b01d-3395b7f26c62">

2. 给导航栏添加 icon 好像不起作用, 这是正常的吗? 如下

<img width="504" alt="图片" src="https://github.com/chengzhongxue/halo-theme-hao/assets/111739721/06f4adff-64d0-4244-95a0-ea889668c0c8">

3. 对文章能否取消随机图片的显示, 或者每篇文章固定为某张图片, 或只显示文字? 以及添加显示summary 这种可选的选项

<img width="1024" alt="图片" src="https://github.com/chengzhongxue/halo-theme-hao/assets/111739721/71171da6-d248-4970-aab4-8cf4602b2254">

十分感谢作者的付出, 有很多不懂, 望解答..

**Comment by carolcoral** [comment]
而且为什么2、3问用的我的博客的截图呢🤔

**Comment by zscmmm** [comment]
方便一些

**Comment by zscmmm** [comment]
> 2. 导航栏目前不支持图标，这个是halo才能操作的，主题没有diy处理
> 
>     3. 每篇文章编辑右上角有一个“设置”，里面下拉有一个封面图设置，可以手动设置每篇文章的封面图

我明白了,十分感谢
