### ISSUE TITLE
标题左侧相关链接不支持icon

### ISSUE THREAD

**Issue by SerMs** [chengzhongxue/halo-theme-hao#760]
### 你当前使用的版本

1.5.3

### 描述一下此特性

**配置icon后不支持，检查代码好像只支持img类型，希望可以加入icon的支持！！**
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/67584847/6674b31c-24d7-44cd-a3c8-f889b6b58db9)
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/67584847/f7e66868-48af-4ae7-81d0-37ee7045ef35)
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/67584847/cb789e73-05a7-4b38-bda7-3c0fa594b144)

**Comment by carolcoral** [comment]
不好处理，暂时不会计划去处理了
