### ISSUE TITLE
markdown的序号渲染不正确

### ISSUE THREAD

**Issue by youngledo** [chengzhongxue/halo-theme-hao#761]
### 是什么版本出现了此问题？

1.5.3

### 发生了什么？

开始以为是markdown插件的原因，经测试是主题的问题：https://github.com/guqing/willow-mde/issues/22

**Comment by carolcoral** [comment]
没有复现，应该你自己的语法没写对
<img width="1008" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/c0581e4a-468d-4ea4-beb4-caf39e11e9fb">

<img width="1426" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/9e37fc7a-3d63-4f00-8bd1-be435cac7dbe">

**Comment by youngledo** [comment]
请问你使用的哪个编辑器？

**Comment by carolcoral** [comment]
原因如下：
如果使用hao主题中的代码块，请关闭`hlight插件`
