### ISSUE TITLE
console和侧栏标签云不显示

### ISSUE THREAD

**Issue by xiaobaisky** [chengzhongxue/halo-theme-hao#763]
### 是什么版本出现了此问题？

 1.5.3

### 发生了什么？

标签云不显示

**Comment by Rampantddd** [comment]
这个对比tags.html可以解决，但是随机颜色失效

**Comment by xiaobaisky** [comment]
> 这个对比tags.html可以解决，但是随机颜色失效

怎么改啊请问

**Comment by gfjz** [comment]
能否给个详细教程？？？

**Comment by gfjz** [comment]
> tags.html

给个详细教程

**Comment by carolcoral** [comment]
<img width="1577" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/6c1585af-4274-406f-8b0a-e6ffd5381ba0">
console显示正确啊

**Comment by carolcoral** [comment]
侧边栏文章标签云也没问题啊

<img width="1680" alt="image" src="https://github.com/chengzhongxue/halo-theme-hao/assets/8952687/ba6dc53c-d7e6-425b-9204-4790c6677967">

**Comment by gfjz** [comment]
> 侧边栏文章标签云也没问题啊
> 
> <img alt="image" width="1680" src="https://private-user-images.githubusercontent.com/8952687/346788759-ba6dc53c-d7e6-425b-9204-4790c6677967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTYzNTgsIm5iZiI6MTcyMDQ5NjA1OCwicGF0aCI6Ii84OTUyNjg3LzM0Njc4ODc1OS1iYTZkYzUzYy1kN2U2LTQyNWItOTIwNC00NzkwYzY2Nzc5NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDMzNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWIzOGVmZTBjMTY4NGU1ZjA0MGExOWFkZTFhNTU3NDk4YWVmNWFjNjc2YjlmNWQ0MmMzMGQ4YzZmYTA1MDI3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r3wIF7FL6qLsmwTJcRZEjnGIvC4Z0gexwIwXTJXugJE">

**Comment by gfjz** [comment]
> 侧边栏文章标签云也没问题啊
> 
> <img alt="image" width="1680" src="https://private-user-images.githubusercontent.com/8952687/346788759-ba6dc53c-d7e6-425b-9204-4790c6677967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTYzNTgsIm5iZiI6MTcyMDQ5NjA1OCwicGF0aCI6Ii84OTUyNjg3LzM0Njc4ODc1OS1iYTZkYzUzYy1kN2U2LTQyNWItOTIwNC00NzkwYzY2Nzc5NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDMzNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWIzOGVmZTBjMTY4NGU1ZjA0MGExOWFkZTFhNTU3NDk4YWVmNWFjNjc2YjlmNWQ0MmMzMGQ4YzZmYTA1MDI3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r3wIF7FL6qLsmwTJcRZEjnGIvC4Z0gexwIwXTJXugJE">

请访问：http://154.64.230.133/

**Comment by gfjz** [comment]
> 侧边栏文章标签云也没问题啊
> 
> <img alt="image" width="1680" src="https://private-user-images.githubusercontent.com/8952687/346788759-ba6dc53c-d7e6-425b-9204-4790c6677967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTYzNTgsIm5iZiI6MTcyMDQ5NjA1OCwicGF0aCI6Ii84OTUyNjg3LzM0Njc4ODc1OS1iYTZkYzUzYy1kN2U2LTQyNWItOTIwNC00NzkwYzY2Nzc5NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDMzNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWIzOGVmZTBjMTY4NGU1ZjA0MGExOWFkZTFhNTU3NDk4YWVmNWFjNjc2YjlmNWQ0MmMzMGQ4YzZmYTA1MDI3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r3wIF7FL6qLsmwTJcRZEjnGIvC4Z0gexwIwXTJXugJE">

看一下console

**Comment by carolcoral** [comment]
你都没开console

**Comment by gfjz** [comment]
> 你都没开console

现在开了，也不行，刚才关了

**Comment by gfjz** [comment]
> 你都没开console

侧边栏最后一个本来是有标签的，现在是没有

**Comment by Rampantddd** [comment]
> <img alt="image" width="1577" src="https://private-user-images.githubusercontent.com/8952687/346788216-6c1585af-4274-406f-8b0a-e6ffd5381ba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTE0MTMsIm5iZiI6MTcyMDUxMTExMywicGF0aCI6Ii84OTUyNjg3LzM0Njc4ODIxNi02YzE1ODVhZi00Mjc0LTQwNmYtOGIwYS1lNmZmZDUzODFiYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDc0NTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU1MzQyMGM4NzMyMzNhNzQwNzA0OWI4MWNkMmJjZTM3ZjcxNTdhNDVlYWNmOTk2ZWYyOThlODI1ZDg0YTU5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JpBtw3JQKK5cqL_31MajAZ-g7Ng6H8L4VmAN6Nm_Kfo"> console显示正确啊

![image](https://github.com/chengzhongxue/halo-theme-hao/assets/124485135/53fee3c7-8195-406f-a02f-90fea2dc4e39)
我是把tags里面的 if 删掉了才显示的，而且那个标签字段原本就是空的

**Comment by Rampantddd** [comment]
> > > <img alt="image" width="1577" src="https://private-user-images.githubusercontent.com/8952687/346788216-6c1585af-4274-406f-8b0a-e6ffd5381ba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTE0MTMsIm5iZiI6MTcyMDUxMTExMywicGF0aCI6Ii84OTUyNjg3LzM0Njc4ODIxNi02YzE1ODVhZi00Mjc0LTQwNmYtOGIwYS1lNmZmZDUzODFiYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDc0NTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU1MzQyMGM4NzMyMzNhNzQwNzA0OWI4MWNkMmJjZTM3ZjcxNTdhNDVlYWNmOTk2ZWYyOThlODI1ZDg0YTU5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JpBtw3JQKK5cqL_31MajAZ-g7Ng6H8L4VmAN6Nm_Kfo"> console显示正确啊
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/124485135/346864559-53fee3c7-8195-406f-a02f-90fea2dc4e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTE1OTUsIm5iZiI6MTcyMDUxMTI5NSwicGF0aCI6Ii8xMjQ0ODUxMzUvMzQ2ODY0NTU5LTUzZmVlM2M3LTgxOTUtNDA2Zi1hMDJmLTkwZmVhMmRjNGUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwNzQ4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTJmNzBhYmY2MzM2ZmUzMjE4NmZiYzRlNjE3MzEyNDIwMzZjZDUyYjZjNjJlODAyMTViMGRjNWMwZDVjMjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pIZC1Kvh1hQ3nyO0x9fIpYkFzh-g6Mpo9ZkCazSLlS8) 我是把tags里面的 if 删掉了侧边栏才显示的，控制台还要另外改，而且那个标签字段原本就是空的
> 
> 控制台怎么改，在哪个文件？他这个我看了一下，找不着

/home/halo/halo2/themes/theme-hao/templates/modules/widgets  这个路径下面

**Comment by gfjz** [comment]
> > <img alt="image" width="1577" src="https://private-user-images.githubusercontent.com/8952687/346788216-6c1585af-4274-406f-8b0a-e6ffd5381ba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTE0MTMsIm5iZiI6MTcyMDUxMTExMywicGF0aCI6Ii84OTUyNjg3LzM0Njc4ODIxNi02YzE1ODVhZi00Mjc0LTQwNmYtOGIwYS1lNmZmZDUzODFiYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDc0NTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU1MzQyMGM4NzMyMzNhNzQwNzA0OWI4MWNkMmJjZTM3ZjcxNTdhNDVlYWNmOTk2ZWYyOThlODI1ZDg0YTU5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JpBtw3JQKK5cqL_31MajAZ-g7Ng6H8L4VmAN6Nm_Kfo"> console显示正确啊
> 
> ![image](https://private-user-images.githubusercontent.com/124485135/346864559-53fee3c7-8195-406f-a02f-90fea2dc4e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTE1OTUsIm5iZiI6MTcyMDUxMTI5NSwicGF0aCI6Ii8xMjQ0ODUxMzUvMzQ2ODY0NTU5LTUzZmVlM2M3LTgxOTUtNDA2Zi1hMDJmLTkwZmVhMmRjNGUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwNzQ4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTJmNzBhYmY2MzM2ZmUzMjE4NmZiYzRlNjE3MzEyNDIwMzZjZDUyYjZjNjJlODAyMTViMGRjNWMwZDVjMjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pIZC1Kvh1hQ3nyO0x9fIpYkFzh-g6Mpo9ZkCazSLlS8) 我是把tags里面的 if 删掉了侧边栏才显示的，控制台还要另外改，而且那个标签字段原本就是空的

if在哪个地方大佬可以圈一下吗？

**Comment by gfjz** [comment]
> > > > <img alt="图像" width="1577" src="https://private-user-images.githubusercontent.com/8952687/346788216-6c1585af-4274-406f-8b0a-e6ffd5381ba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTE0MTMsIm5iZiI6MTcyMDUxMTExMywicGF0aCI6Ii84OTUyNjg3LzM0Njc4ODIxNi02YzE1ODVhZi00Mjc0LTQwNmYtOGIwYS1lNmZmZDUzODFiYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDc0NTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU1MzQyMGM4NzMyMzNhNzQwNzA0OWI4MWNkMmJjZTM3ZjcxNTdhNDVlYWNmOTk2ZWYyOThlODI1ZDg0YTU5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JpBtw3JQKK5cqL_31MajAZ-g7Ng6H8L4VmAN6Nm_Kfo">console显示正确啊
> > > 
> > > 
> > > ![图像](https://private-user-images.githubusercontent.com/124485135/346864559-53fee3c7-8195-406f-a02f-90fea2dc4e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTE1OTUsIm5iZiI6MTcyMDUxMTI5NSwicGF0aCI6Ii8xMjQ0ODUxMzUvMzQ2ODY0NTU5LTUzZmVlM2M3LTgxOTUtNDA2Zi1hMDJmLTkwZmVhMmRjNGUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwNzQ4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTJmNzBhYmY2MzM2ZmUzMjE4NmZiYzRlNjE3MzEyNDIwMzZjZDUyYjZjNjJlODAyMTViMGRjNWMwZDVjMjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pIZC1Kvh1hQ3nyO0x9fIpYkFzh-g6Mpo9ZkCazSLlS8)我是把tags里面的 if 删掉了侧边栏才显示的，控制台还要改另外，而且那个标签字段原本就是空的
> > 
> > 
> > 控制台怎么改，在哪个文件？他这个我看了一下，找不着
> 
> /home/halo/halo2/themes/theme-hao/templates/modules/widgets 这个路径下面

那个文件大佬有没有模板可以改的，能不能发到：994923161@qq.com在这个邮箱，就是这个侧边栏的文件和那个console的文件
