### ISSUE TITLE
建议优化一下外部链接之类的

### ISSUE THREAD

**Issue by luoye9711** [chengzhongxue/halo-theme-hao#767]
### 你当前使用的版本

1.5.4

### 描述一下此特性

使用外部资源 打开F12 就几十条Third-party cookie will be blocked. Learn more in the Issues tab. 
和
' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
弹出来。使用本地资源的话也是 几十条Third-party cookie will be blocked. Learn more in the Issues tab. ，虽然不影响正常访问吧，但这东西他影响seo

### 附加信息

![Uploading 147.png…]()

**Comment by luoye9711** [comment]
![147](https://github.com/chengzhongxue/halo-theme-hao/assets/111424865/bfcd34c2-3f6b-4fc0-af43-a621eecd1cc6)

**Comment by carolcoral** [comment]
这是他自己的站点出现问题，和主题没关系
