### ISSUE TITLE
自定义页脚padding高度后，页脚宽度不稳定

### ISSUE THREAD

**Issue by ahhuipt** [chengzhongxue/halo-theme-hao#768]
### 是什么版本出现了此问题？

1.5.4

### 在线站点地址

https://gyhwd.top/

### 发生了什么？

自定义页脚padding高度为0后，鼠标从上面划到页脚过程中，页脚会一瞬间从宽的变成窄的，正常情况下应该一直是窄的

**Comment by ahhuipt** [comment]
<img width="1271" alt="Snipaste_2024-06-30_23-44-46" src="https://github.com/chengzhongxue/halo-theme-hao/assets/130829182/e2a7b364-d89a-46c4-93ee-47a5eb682050">

**Comment by carolcoral** [comment]
你再试试呢，或者刷新下缓存，我刚才点你网站没有复现

**Comment by ahhuipt** [comment]
哥，问题是存在的，你先用鼠标划上去，然后划到页面低端，重复就能看到

**Comment by carolcoral** [comment]
录制: 沉默の大多数
录制文件：https://meeting.tencent.com/v2/cloud-record/share?id=yLXA5dmfB3un5R0bFRAbbal9yDWI_DiU8X00ZhiOe78&from=3&record_type=1&is-single=true
有效期：于2024-07-08 16:08:42过期

操作了，没复现

**Comment by ahhuipt** [comment]
https://cowtransfer.com/s/ca5994d4cf234b 点击链接查看 [ 演示.mp4 ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 4k3k15 查看；

**Comment by carolcoral** [comment]
> https://cowtransfer.com/s/ca5994d4cf234b 点击链接查看 [ 演示.mp4 ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 4k3k15 查看；

图片大小导致的，但是这个大小限制在很早前的版本就做了的，高度限制不会影响这个地方，你看看是不是服务缓存、服务器缓存、本地缓存问题呢。另外，因为npm被封锁，建议资源使用`本地`资源试试

**Comment by ahhuipt** [comment]
> > https://cowtransfer.com/s/ca5994d4cf234b 点击链接查看 [ 演示.mp4 ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 4k3k15 查看；
> 
> 图片大小导致的，但是这个大小限制在很早前的版本就做了的，高度限制不会影响这个地方，你看看是不是服务缓存、服务器缓存、本地缓存问题呢。另外，因为npm被封锁，建议资源使用`本地`资源试试

我把云服务显示功能关掉就好了

**Comment by carolcoral** [comment]
> > > https://cowtransfer.com/s/ca5994d4cf234b 点击链接查看 [ 演示.mp4 ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 4k3k15 查看；
> > 
> > 
> > 图片大小导致的，但是这个大小限制在很早前的版本就做了的，高度限制不会影响这个地方，你看看是不是服务缓存、服务器缓存、本地缓存问题呢。另外，因为npm被封锁，建议资源使用`本地`资源试试
> 
> 我把云服务显示功能关掉就好了

因为你这个问题就是云服务显示的那个图片导致的，主题做了大小限制，但是不知道为什么你的没生效
