### ISSUE TITLE
建议优化一下CND地址

### ISSUE THREAD

**Issue by jianxuanbing** [chengzhongxue/halo-theme-hao#771]
### 是什么版本出现了此问题？

1.5.4

### 发生了什么？

`1.5.3`、`1.5.4` 版本均出现该问题
访问 `npm.onmicrsoft.cn` 出现 404 响应异常
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/7100363/c1918f01-3954-4a55-8519-2273e5d67f26)

**Comment by carolcoral** [comment]
从1.5.3开始不再使用CDN地址，后续版本会取消该选项和设置，请使用`本地`资源
