### ISSUE TITLE
从1.5.2更新到1.5.4（Halo 2.17.0）之后出现全站页面渲染错误

### ISSUE THREAD

**Issue by PatZer0** [chengzhongxue/halo-theme-hao#774]
### 是什么版本出现了此问题？

1.5.4

### 在线站点地址

https://patzer0.com

### 发生了什么？

Halo版本2.17.0，之前使用的主题1.5.2版本没有问题，当更新到1.5.4之后出现了全站页面渲染异常的问题。
但是切换到默认Earth主题没有这个问题，因此怀疑是主题的问题导致，尝试降级到1.5.3，问题依旧，降级到1.5.2之后问题解决，但不知道是哪里出了问题。

![PixPin_2024-07-05_18-51-27](https://github.com/chengzhongxue/halo-theme-hao/assets/96248319/4f009bc5-e56f-43c4-abe0-b79dac0f16a7)
![PixPin_2024-07-05_18-52-17](https://github.com/chengzhongxue/halo-theme-hao/assets/96248319/a8f2a936-61ab-4d59-90b1-e64c201a39c9)
![PixPin_2024-07-05_18-52-43](https://github.com/chengzhongxue/halo-theme-hao/assets/96248319/e70840dc-9a87-4a08-95ca-e589c3728b35)

### 相关日志输出

```shell
Halo后台下载日志没有发现关于主题的报错。
```

**Comment by ahhuipt** [comment]
把静态资源文件选择本地就好了，
![image](https://github.com/chengzhongxue/halo-theme-hao/assets/130829182/34488534-91c8-4392-896f-13188897123a)

**Comment by PatZer0** [comment]
> 把静态资源文件选择本地就好了， ![image](https://private-user-images.githubusercontent.com/130829182/346244134-34488534-91c8-4392-896f-13188897123a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODM4NTUsIm5iZiI6MTcyMDI4MzU1NSwicGF0aCI6Ii8xMzA4MjkxODIvMzQ2MjQ0MTM0LTM0NDg4NTM0LTkxYzgtNDM5Mi04OTZmLTEzMTg4ODk3MTIzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNjMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTZkOWUzNjVkYTU4ZjMxNDJiMDE4MDhlZDExMWRmZGY5ZTU1MzAyN2I0NmQwNWUxODE4YjI4Yjc0ZGUwNGY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g2NFNpkpwuGW1tsmh1KTqZvl1hRk-DNbzKeHt1kZq0Y)

选择为本地没效果，还是一样，无痕模式也是一样
![PixPin_2024-07-07_00-32-08](https://github.com/chengzhongxue/halo-theme-hao/assets/96248319/14afeba1-b448-49bd-9f0d-a80787f40cd1)
![PixPin_2024-07-07_00-33-44](https://github.com/chengzhongxue/halo-theme-hao/assets/96248319/2438081b-c7b8-4f03-920a-9d18ca85f2e6)

**Comment by jianxuanbing** [comment]
遇到一样的问题

**Comment by carolcoral** [comment]
静态资源的问题，选择主题设置中`本地`资源
1. 清空缓存
2. 重启容器
3. 如果存在CDN请刷新CDN

**Comment by carolcoral** [comment]
另外，因为NPM封锁了国内使用，后面所有版本不再提供NPM加速，只提供`本地`、`自定义`模式了

**Comment by carolcoral** [comment]
请更新1.5.5版本，只允许本地模式或自定义模式，不再提供npm方式
