### ISSUE TITLE
页面配置问题

### ISSUE THREAD

**Issue by gfjz** [chengzhongxue/halo-theme-hao#780]
### 是什么版本出现了此问题？

1.5.5

### 在线站点地址

http://154.64.230.133/

### 发生了什么？

本主题的我的装备界面怎么配置，未设置模板

**Comment by carolcoral** [comment]
“我的装备”很早前的版本就已经变更为插件方式使用了，请查看readme.md文档中相关插件说明

**Comment by gfjz** [comment]
> “我的装备”很早前的版本就已经变更为插件方式使用了，请查看readme.md文档中相关插件说明

那请问插件如何生成页面访问呢
