### ISSUE TITLE
关于修复tags全局组件无法显示的bug-致官方-请尽快修复

### ISSUE THREAD

**Issue by gfjz** [chengzhongxue/halo-theme-hao#781]
### 你当前使用的版本

1.5.6

### 描述一下此特性

麻烦官方修改bug：
修改文件：theme-hao/templates/modules/widgets/aside/contain/tags-contain.html
修改文件：theme-hao/templates/modules/widgets/console.html
我会将修复bug后的文件上传至https://www.123pan.com/s/Hal7jv-EEG2.html 提取码:1234，官方如收到更新后麻烦发我邮箱：994923161@qq.com
我更新主题，不然我动不了

**Comment by gfjz** [comment]
补充一下，还有一个移动版的tags bug ，我还是上传到上面的链接了哈

**Comment by carolcoral** [comment]
@chengzhongxue
