### ISSUE TITLE
新建了友情链接页面，打开评论功能仍然不显示评论，导致点击申请友情链接按钮，无法跳转

### ISSUE THREAD

**Issue by GuGuGee** [chengzhongxue/halo-theme-hao#782]
### 是什么版本出现了此问题？

1.5.6

### 在线站点地址

https://blog.laoda.de/links

### 发生了什么？

您好，我创建了友情链接页面，打开评论功能，发现仍然不显示评论，导致点击申请友情链接按钮，无法跳转。

![image](https://github.com/user-attachments/assets/ca6b8432-ba07-4521-bffa-3ba2518dc59f)

![image](https://github.com/user-attachments/assets/3689f2c4-e691-4ed4-8521-62b420056bc6)

halo版本信息：

![image](https://github.com/user-attachments/assets/a2b8bd05-e862-4b47-b8f9-b985027efedd)

**Comment by carolcoral** [comment]
没有复现，你是不是在主题设置里面友链加了什么设置

**Comment by carolcoral** [comment]
当前主题已不是hao主题，关闭issue了
