### ISSUE TITLE
hao手机端侧边栏不显示，是什么原因导致的啊

### ISSUE THREAD

**Issue by atangccc** [chengzhongxue/halo-theme-hao#784]
![1720847149903](https://github.com/user-attachments/assets/c8704664-b6c5-47d2-971f-d93a02b526e2)

**Comment by carolcoral** [comment]
要设置左侧菜单，并且必须是二级菜单才能生效

**Comment by atangccc** [comment]
> 要设置左侧菜单，并且必须是二级菜单才能生效
效

已解决
