### ISSUE TITLE
页脚 CC 协议图标被焊死无法修改

### ISSUE THREAD

**Issue by Ghost-chu** [chengzhongxue/halo-theme-hao#785]
### 是什么版本出现了此问题？

1.5.6

### 发生了什么？

即使我使用的不是 CC BY-NC-ND 协议，但页脚仍然显示的是 CC BY-NC-ND 的图标。

经查询，在模板里焊死了：https://github.com/chengzhongxue/halo-theme-hao/blob/5d990944bae9139a9da9a3f0665c4b0b7a67bc5e/templates/modules/footer.html#L191-L194

**Comment by carolcoral** [comment]
这个目前不太考虑去支持动态设置CC图标，目前的主题设置已经太多了，后面都打算进行精简了

**Comment by Ghost-chu** [comment]
> 这个目前不太考虑去支持动态设置CC图标，目前的主题设置已经太多了，后面都打算进行精简了

那能否改成只有一个 CC 图标？现在这样明确指定 CC 协议图标容易引起误解。这是一个有关知识产权和法律的问题，还希望能够考虑一下。

**Comment by carolcoral** [comment]
你可以自己改下这块内容，然后打成压缩包就可以直接上传使用了，只需要压缩以下4个文件/文件夹
<img width="906" alt="image" src="https://github.com/user-attachments/assets/8ddaad5e-c256-4898-ac51-0b82dd6cbda0">
