### ISSUE TITLE
文章渲染影响图片素材进行懒加载

### ISSUE THREAD

**Issue by hunteris666** [chengzhongxue/halo-theme-hao#786]
### 是什么版本出现了此问题？

 2.17.1，版本 1.5.6

### 发生了什么？

当全篇文章无markdown渲染的时候右侧头像，贴纸，版权信息上方的图片均可正常加载。
反之，文章有markdown时上述图片均无法正常加载，状态为404或空白。

**Comment by hunteris666** [comment]
自查了一下，渲染的<img>里面有个叫data-lazy-src的东西，应该对应一个叫懒加载的功能，关闭懒加载即修复。
貌似懒加载不能在文章页面有markdown的情况下开启，开启则不能正常加载图片。

**Comment by carolcoral** [comment]
这个头像么？可以加载啊 https://oyiso.xindu.site/archives/1717550409834
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/4cadab58-7384-469b-a478-d5815b49bf2e">

页脚也没看到什么问题啊
<img width="1661" alt="image" src="https://github.com/user-attachments/assets/de3b9087-45a7-45ca-98ad-2a09d32d9cb2">
