### ISSUE TITLE
编辑按钮：电脑端有，手机端没有

### ISSUE THREAD

**Issue by simanya2** [chengzhongxue/halo-theme-hao#787]
### 是什么版本出现了此问题？

编辑按钮：电脑端有，手机端没有

### 发生了什么？

可否在手机端加个编辑按钮，点击跳转到当前文章的后台编辑页面，手机可以随时带着，随时编辑文章，个人觉得这样更方便
![P_2024-07-24_14-56-06](https://github.com/user-attachments/assets/1ceb7d28-8706-4196-9217-dc537afbeb7e)
![P_2024-07-24_15-05-25](https://github.com/user-attachments/assets/3e13d7bc-ed5b-44ef-99fa-2425e7ec1478)

**Comment by carolcoral** [comment]
手机上编辑文章不觉得很麻烦、很难受吗

**Comment by simanya2** [comment]
还行，记个笔记啥的挺方便的，或者电脑懒得开机了，文章需要稍微改下，马上就改完了，省时间哈

**Comment by carolcoral** [comment]
后面有空去改下，css改改就行

**Comment by simanya2** [comment]
谢啦

**Comment by carolcoral** [comment]
移动端情况下有登陆按钮的，你看看是不是你头像的问题
![image](https://github.com/user-attachments/assets/c10a60ee-47f6-4b55-9aee-6e1cfda2f5f8)
