### ISSUE TITLE
waline 的最新版是 3. 而插件用的是 2

### ISSUE THREAD

**Issue by zscmmm** [chengzhongxue/halo-theme-hao#795]
### 你当前使用的版本

1.5.7

### 描述一下此特性

看了一下源码, 引入的是版本 2:   https://cdn.cbd.int/@waline/client@2.15.7/dist/waline.js

由于V3 和 v2 的语法可能不同, 导致不能直接使用 v3 的 js 和 css. 望修复. 感谢您的付出.

**Comment by carolcoral** [comment]
hao主题自己可以选择使用`默认`、`twikoo`、`artalk`、`waline`评论插件的，主题里面使用的时候关闭对应的第三方评论插件就行
