### ISSUE TITLE
关于1.5.7版本之后文章版权样式二中打赏连接周围按钮失效

### ISSUE THREAD

**Issue by lycoriskang** [chengzhongxue/halo-theme-hao#796]
### 是什么版本出现了此问题？

1.5.7-1.5.8

### 发生了什么？

我设置了样式2并且1开启了“分享到手机”“分享到微博”的按钮，但是只有打赏按钮是正常的

### 附加信息

![微信图片_20240830233920](https://github.com/user-attachments/assets/0e42377c-17c1-402e-82ee-28e7d3a24195)

**Comment by carolcoral** [comment]
图标库无效了，用本地图标库试试

**Comment by lycoriskang** [comment]
> 图标库无效了，用本地图标库试试

没有找到图标库配置位置，或解决方法

**Comment by carolcoral** [comment]
分享按钮正常的啊 https://blog.xindu.site/archives/1724229233848?preview-theme=theme-hao
<img width="892" alt="image" src="https://github.com/user-attachments/assets/a6334afd-9f65-4f39-bb0b-6e528ab7615a">

**Comment by lycoriskang** [comment]
哦哦哦，被AdGuard拦截了
