### ISSUE TITLE
每秒都在请求上班时间与下班时间的徽标

### ISSUE THREAD

**Issue by ccd2s** [chengzhongxue/halo-theme-hao#799]
### 是什么版本出现了此问题？

Halo:2.19.1   主题:1.5.8

### 在线站点地址

https://www.tasaed.top/

### 发生了什么？

![msedge_lBTGuAjmbp](https://github.com/user-attachments/assets/b1225d19-da25-4381-8b83-90958beb07d0)

如上图，每秒都在请求上班时间与下班时间的徽标，非常占用服务器资源，目前没有任何报错和日志

**Comment by carolcoral** [comment]
你可以关闭这个功能，设置-页脚里面控制。
不每秒请求怎么知道现在的时间呢，数据返回给浏览器后是udp通信，又不是ftp通信

**Comment by carolcoral** [comment]
当然，也可以本地获取时间后去判断时候需要请求，但是这个已经是历史遗留问题了，现在大概率不会去处理了
