### ISSUE TITLE
最新版主菜单下二级菜单图标无法正常显示

### ISSUE THREAD

**Issue by SuperJeason** [chengzhongxue/halo-theme-hao#800]
### 是什么版本出现了此问题？

hao 1.5.8  

### 在线站点地址

http://39.101.75.112:6090/

### 发生了什么？

主菜单图标异常，副菜单正常，为方便展示，已将主菜单和站点名左侧菜单设置相同
![PixPin_2024-09-12_00-05-26](https://github.com/user-attachments/assets/654a6322-77ff-448e-ab10-7efde86c5808)
![PixPin_2024-09-12_00-07-39](https://github.com/user-attachments/assets/9ef31570-93bf-4fdd-adea-13899004a79b)

**Comment by carolcoral** [comment]
左侧菜单用的是图片，顶部菜单用的是icon图标，可以使用iconfont图标（需要自行引入）
