### ISSUE TITLE
顶部Banner左侧背景图选择个人技术栈时显示问题

### ISSUE THREAD

**Issue by LTUUCN** [chengzhongxue/halo-theme-hao#801]
### 是什么版本出现了此问题？

1.5.8

### 发生了什么？

1. 顶部Banner左侧背景图选择个人技术栈时，首页的图标不显示。
2. 选择垂直滚动时，图标还是倾斜的，关于界面图标也是倾斜的。
3. 建议添加图标技能少的情况下，图标可以自己重复，否则图标太少不够美观；重复添加的话，关于界面的技能也会重复。

**Comment by carolcoral** [comment]
1. 选择个人技术栈需要手动添加图标
2. 这个问题上次改出来的，一直没空去修复
3. 鱼说的这种问题暂时不会处理的
