### ISSUE TITLE
关于页面问题

### ISSUE THREAD

**Issue by Leif-cmd** [chengzhongxue/halo-theme-hao#802]
### 是什么版本出现了此问题？

halo>2.19.3 hao>1.58

### 在线站点地址

https://leif.us.kg

### 发生了什么？

/about页面为404
![屏幕截图 2024-09-17 230312](https://github.com/user-attachments/assets/e3c8f7dd-e757-49fe-870e-07a824dce36a)

**Comment by carolcoral** [comment]
https://www.yuque.com/liuzhihangs/halo-theme-hao/eeoayhggq5a7wh3u
