### ISSUE TITLE
使用Artalk评论系统（2.9.1）时仪表板无法显示最新评论

### ISSUE THREAD

**Issue by PatZer0** [chengzhongxue/halo-theme-hao#805]
### 是什么版本出现了此问题？

1.5.8

### 在线站点地址

https://patzer0.com

### 发生了什么？

例如页面：https://patzer0.com/archives/circadian-lighting-color-temperature-throughout-the-day-by-using-mijia-automation-geek-edition
在此页面中有评论，但仪表板中没有显示最近评论，是否是已经不适配新版Artalk？
此外，在主题中配置Artalk时必须手动指定对应版本的Artalk资源文件（js&css），否则会出错。
开发者工具发现尝试请求latest_comments报错
![image](https://github.com/user-attachments/assets/b4203fa4-a928-488c-8f87-184ed288a6ce)

![image](https://github.com/user-attachments/assets/e30833d0-afe2-4cf0-887e-e2ecd97517fb)
![1727149979886](https://github.com/user-attachments/assets/985c209c-6e02-4ac9-817a-91d440bb986c)

**Comment by chengzhongxue** [comment]
第三方评论时仪表板本来就无法显示

**Comment by chengzhongxue** [comment]
不是官方评论都不会在哪里有
