### ISSUE TITLE
支持 highlight.js插件

### ISSUE THREAD

**Issue by hiyms** [chengzhongxue/halo-theme-hao#807]
### 你当前使用的版本

1.5.8

### 描述一下此特性

我注意到hao所支持的prism.js 代码高亮插件在halo 2.19.3中无法正常工作，会导致HTTP ERROR 500错误，且该插件最后一次更新在两年前。
而当使用halo官方提供的highlight.js 代码高亮插件时，文章中的代码块并没有高亮（已启用主题侧渲染）。

**Comment by carolcoral** [comment]
主题内置了代码高亮功能
