### ISSUE TITLE
好像首页顶上，左右区域图那里，就是瞬间的下面。那个区域划到的时候鼠标滚不动，过不去。得点其他区域才能继续。

### ISSUE THREAD

**Issue by aimenglang** [chengzhongxue/halo-theme-hao#808]
### 是什么版本出现了此问题？

2.19

### 发生了什么？

好像首页顶上，左右区域图那里，就是瞬间的下面。那个区域划到的时候鼠标滚不动，过不去。得点其他区域才能继续。

**Comment by carolcoral** [comment]
你截图具体位置看看，或者给个录屏，目前测试没发现问题 https://blog.xindu.site/?preview-theme=theme-hao

**Comment by aimenglang** [comment]
> 你截图具体位置看看，或者给个录屏，目前测试没发现问题https://blog.xindu.site/?preview-theme=theme-hao
<img width="1217" alt="image" src="https://github.com/user-attachments/assets/54286441-d195-4278-bd91-d583537a63cb">

顶上左右两边的区域，鼠标在上面使用滚动方式，是滚动不了的。。

https://github.com/user-attachments/assets/c749b6ba-7a4c-4c56-bdfb-96a974e68921

视频压缩了。要不然传不上来。但是能看道具体操作。就是其他区域可以鼠标滚动。。就那两个区域不行。

**Comment by carolcoral** [comment]
我试了下，没有复现这个问题，你让你朋友访问也试试呢
![luping](https://api.minio.cnkj.site/blog.cnkj.site/cache/%E5%BD%95%E5%B1%8F2024-10-09%2009.36.39%20-%20Compressed%20with%20FlexClip.mp4)

**Comment by aimenglang** [comment]
> 我试了下，没有复现这个问题，你让你朋友访问也试试呢
> 
> 如果看不到下面的视频，可以访问[地址](https://api.minio.cnkj.site/blog.cnkj.site/cache/%E5%BD%95%E5%B1%8F2024-10-09%2009.36.39%20-%20Compressed%20with%20FlexClip.mp4)查看

哈哈，，你不会用的firefox吧？。。我试了。用edge或Firefox可以，，但是用chrome和safari都会出现。。
也没啥事，遇到了就反馈一下。哈哈。。

**Comment by carolcoral** [comment]
> > 我试了下，没有复现这个问题，你让你朋友访问也试试呢
> > 如果看不到下面的视频，可以访问[地址](https://api.minio.cnkj.site/blog.cnkj.site/cache/%E5%BD%95%E5%B1%8F2024-10-09%2009.36.39%20-%20Compressed%20with%20FlexClip.mp4)查看
> 
> 哈哈，，你不会用的firefox吧？。。我试了。用edge或Firefox可以，，但是用chrome和safari都会出现。。 也没啥事，遇到了就反馈一下。哈哈。。

我用的chrome和safari，mac系统

**Comment by carolcoral** [comment]
<img width="736" alt="image" src="https://github.com/user-attachments/assets/cb5e4248-baa4-46c8-b8c5-287c789aaf2f">
<img width="266" alt="image" src="https://github.com/user-attachments/assets/2bb20917-054b-4bf3-b042-cb3471f1c9f9">

**Comment by aimenglang** [comment]
> > > 我试了下，没有复现这个问题，你让你朋友访问也试试呢
> > > 如果看不到下面的视频，可以访问[地址](https://api.minio.cnkj.site/blog.cnkj.site/cache/%E5%BD%95%E5%B1%8F2024-10-09%2009.36.39%20-%20Compressed%20with%20FlexClip.mp4)查看
> > 
> > 
> > 哈哈，，你不会用的firefox吧？。。我试了。用edge或Firefox可以，，但是用chrome和safari都会出现。。 也没啥事，遇到了就反馈一下。哈哈。。
> 
> 我用的chrome和safari，mac系统

<img width="796" alt="截屏2024-10-11 16 00 36" src="https://github.com/user-attachments/assets/05afbd56-11bc-431b-9074-e444b4a8ca50">
<img width="290" alt="image" src="https://github.com/user-attachments/assets/5d19d657-d966-4cf8-a276-5d3839df354f">

我用的chrome和safari版本是截图上的。我还换了Windows的chrome试了。。

我确实有出现。那没啥事情了，，有劳了。哈哈。。

**Comment by carolcoral** [comment]
@aimenglang 没事，主要我确实在windows和mac都试过，确实没法复现，就帮不到你了，后续你试试重装主题能不能修复
