### ISSUE TITLE
站内搜索无效

### ISSUE THREAD

**Issue by Nodewebzsz** [chengzhongxue/halo-theme-hao#816]
### 是什么版本出现了此问题？

 2.20.7

### 在线站点地址

https://blog.zszweb.cn/

### 发生了什么？

站内搜索文章搜不到
![1729922562838](https://github.com/user-attachments/assets/4568382e-6bec-4b67-94c2-77992a02c6e0)
![1729923004395](https://github.com/user-attachments/assets/f302aa73-949f-41e7-b5df-c677205a9075)

**Comment by carolcoral** [comment]
登陆后台，点`刷新搜索引擎`
<img width="714" alt="image" src="https://github.com/user-attachments/assets/be01dc7b-0a8e-43d2-955a-86bd403b5e82">
