### ISSUE TITLE
首页显式的文章数量可以调整吗

### ISSUE THREAD

**Issue by lycoris-xmin** [chengzhongxue/halo-theme-hao#819]
### 你当前使用的版本

1.6.0

### 描述一下此特性

我首页的侧栏东西有点多，首页目前显示的文章数量，会导致侧栏过长，文章列表底部有一部是空白的

**Comment by carolcoral** [comment]
目前不能调整，主题里面是固定的10篇文章

**Comment by lycoris-xmin** [comment]
好的吧，谢谢哈

**Comment by carolcoral** [comment]
你要的话可以找我给你单独弄个，只要一个爱发电就行 https://afdian.com/a/carolcoral
