### ISSUE TITLE
新增支持切换首页左侧banner滚动样式，在后台没看到有切换的地方欸

### ISSUE THREAD

**Issue by gym02** [chengzhongxue/halo-theme-hao#821]
### 是什么版本出现了此问题？

 1.6.0

### 在线站点地址

https://gavana.top/

### 发生了什么？

1.5 版本新增支持切换首页左侧banner滚动样式，我安装的1.6.0 版本在后台没看到有切换的地方欸

**Comment by gym02** [comment]
我想让首页左侧banner，图标滚动快一点

**Comment by carolcoral** [comment]
目前不管哪个版本都不支持调整滚动速度，另外因为部分兼容问题，滚动样式切换在1.6.0版本被删除了，最新的支持切换样式的版本是1.5.9
