### ISSUE TITLE
移动端打开第一屏，点击首页加载动画、加载条乱跳。

### ISSUE THREAD

**Issue by Rocky-Edc** [chengzhongxue/halo-theme-hao#822]
### 是什么版本出现了此问题？

1.6.0

### 发生了什么？

访问了相同主题的其他人，均存在此情况。
https://github.com/user-attachments/assets/33d187df-ee40-447c-8be4-8c03c36d3dff

**Comment by carolcoral** [comment]
不太明白，看了录制视频，没发现什么问题啊

**Comment by Rocky-Edc** [comment]
> 不太明白，看了录制视频，没发现什么问题啊

> > 点击首页时，就是加载动画开始是位于中间，一会过后就会往右下角移动。其他页面正常
