### ISSUE TITLE
移动端无法切换显示模式

### ISSUE THREAD

**Issue by Rocky-Edc** [chengzhongxue/halo-theme-hao#823]
### 是什么版本出现了此问题？

1.6.0

### 在线站点地址

https://attempt.site/

### 发生了什么？

点击切换显示模式时，抛出如下错误。
（索引）:696 Uncaught ReferenceError: rm is not defined
    at HTMLAnchorElement.onclick (（索引）:696:55)
![image](https://github.com/user-attachments/assets/d4ed67c3-3c7a-4b92-9230-aaa2432ea4a7)

**Comment by Rocky-Edc** [comment]
复现步骤：
1：打开小部件的右键菜单，保存。此时能够正常切换显示模式
2：关闭小部件的右键菜单，保存。此时就会出现上述的问题。

**Comment by carolcoral** [comment]
<img width="1231" alt="image" src="https://github.com/user-attachments/assets/91d17475-6c7c-46e5-8fcf-408c54f6b584">
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/8e24b340-d78e-4be6-950d-ec4c5d0ff009">

**Comment by Rocky-Edc** [comment]
> <img width="1231" alt="image" src="https://github.com/user-attachments/assets/91d17475-6c7c-46e5-8fcf-408c54f6b584">
> <img width="1158" alt="image" src="https://github.com/user-attachments/assets/8e24b340-d78e-4be6-950d-ec4c5d0ff009">
> 

现在已经打开了PC端的右键菜单，若我关闭就会出现这个错误

**Comment by Rocky-Edc** [comment]
> 复现步骤：
> 1：打开小部件的右键菜单，保存。此时能够正常切换显示模式
> 2：关闭小部件的右键菜单，保存。此时就会出现上述的问题。

> > 现在已经打开了pc的右键菜单小部件，所以没有报错了。如果关闭就会出现错误

**Comment by KingStoning** [comment]
> > 复现步骤：
> > 1：打开小部件的右键菜单，保存。此时能够正常切换显示模式
> > 2：关闭小部件的右键菜单，保存。此时就会出现上述的问题。
> 
> > > 现在已经打开了pc的右键菜单小部件，所以没有报错了。如果关闭就会出现错误

你好，请问你的问题解决了吗

**Comment by Rocky-Edc** [comment]
> > > 复现步骤：
> > > 1：打开小部件的右键菜单，保存。此时能够正常切换显示模式
> > > 2：关闭小部件的右键菜单，保存。此时就会出现上述的问题。
> > 
> > > > 现在已经打开了pc的右键菜单小部件，所以没有报错了。如果关闭就会出现错误
> 
> 你好，请问你的问题解决了吗
您好，已经解决了，我自己修改了一些相关的样式定义
