### ISSUE TITLE
标签页/分类页无法加载文章的图片

### ISSUE THREAD

**Issue by Emrys-a** [chengzhongxue/halo-theme-hao#827]
### 是什么版本出现了此问题？

1.6.0

### 在线站点地址

https://ouo.st/categories/default

### 发生了什么？

![屏幕截图 2024-11-10 212541](https://github.com/user-attachments/assets/e626709e-2e2f-49e3-a840-99afa2d54fa2)
主图只会展示一帧，然后就显示错误

**Comment by carolcoral** [comment]
没有问题，建议检查网络或者图片设置
<img width="1417" alt="image" src="https://github.com/user-attachments/assets/849de32e-87fb-4dc2-ae92-e298cc4d2ddd">
