### ISSUE TITLE
个人名片添加“个人头像”和个人名称

### ISSUE THREAD

**Issue by chengzequn** [chengzhongxue/halo-theme-hao#831]
### 描述一下此特性

![image](https://github.com/user-attachments/assets/c85b3a3c-702b-46cd-bd8d-328ee168448c)
如图现在版本中显示的是网站的名称和网站的头像，可否添加个属性以显示个人头像和个人名称

**Comment by carolcoral** [comment]
个人头像和个人名称属于登陆后的内容，这部分展示目前是在登陆后的站点的右上角展示的

**Comment by chengzequn** [comment]
最后选择将logo作为了头像，Favicon作为网站logo
![image](https://github.com/user-attachments/assets/f3641114-3ce4-4436-831d-591ca4b89fda)
