### ISSUE TITLE
顶部设置中，希望能支持banner左侧可配置，可隐藏

### ISSUE THREAD

**Issue by sunkolin** [chengzhongxue/halo-theme-hao#843]
### 你当前使用的版本

1.6.1

### 描述一下此特性

顶部设置中，希望能支持banner左侧可配置，可隐藏。
<img width="683" alt="image" src="https://github.com/user-attachments/assets/9339428c-d359-4755-ab1d-be89ebb278a2">

**Comment by carolcoral** [comment]
这个暂时不会考虑，单独设置会严重影响整体顶部的布局设置的

**Comment by sunkolin** [comment]
或者可以支持设置成随机推荐一篇文章，或者设置成固定一篇文章。必看，热门这两个按钮太小了。想看需要专门鼠标移过去。这块希望能支持整张图可点，直接跳转一个内容。

**Comment by carolcoral** [comment]
文字可以长一点
